### ISSUE TITLE
Groom Scrum Board, moving Issues to Review, and including Tangible Assets. Time boxed README entries that point to Issues by wednesday

### ISSUE THREAD

**Issue by ryanmgds** [jli615/lebroncs#19]
link to code: https://github.com/jli615/lebroncs/blob/main/src/main/java/com/example/sping_portfolio/controllers/Stats.java 

https://github.com/jli615/lebroncs/blob/main/src/main/resources/templates/statsBB.html

**Comment by jm1021** [comment]
Groom looks good, assignments discussed 1.0 + 0.5 extra credit from Adi by completing minilab

**Comment by jli615** [comment]
Ridhima and Sam graded, 9.5/10 
Unit 4 - everybody had notes and correction 5/5
Issues on Scrum Board 3/3
Individual technical 1/2 - had the tickets on the scrum board (look at twitter to understand)
Extra credit - 0.5 pts
