### ISSUE TITLE
Week 7 Review Ticket

### ISSUE THREAD

**Issue by jli615** [jli615/lebroncs#37]
Rohan N [journal](https://docs.google.com/document/d/1Dgo7CY2jxnVj65bZKBA6qgkrpPXyoRsbat23JUp7-yU/edit) - Created the recursion function using Boolean variable: 
- [x] [front end](https://github.com/jli615/lebroncs/blob/main/src/main/resources/templates/image.html#L17-L22)
- [x] [back end](https://github.com/jli615/lebroncs/blob/main/src/main/java/com/example/sping_portfolio/controllers/grayscale.java#L21-L26)

Justin [journal](https://docs.google.com/document/d/1OPRMwOUsIXQAviD770tt6ad24YB9dVeR5SI8XWJzHYs/edit?usp=sharing) - Consolidated the @getmappings into one and made the if else logic utilizing the created toggle(boolean) variable:
- [x] [if for colored images](https://github.com/jli615/lebroncs/blob/main/src/main/java/com/example/sping_portfolio/controllers/grayscale.java#L32)
- [x] [else for grayscale](https://github.com/jli615/lebroncs/blob/main/src/main/java/com/example/sping_portfolio/controllers/grayscale.java#L75)

Ryan [journal](https://docs.google.com/document/d/1c0jHTO8-ny1ojF077amTJ0aANaYlL44gPX6CZOGkgEM/edit) - Added in 10 png images that can be appended to the array list for use in displaying color and grayscale on website:
- [x] [pngs for colored array list](https://github.com/jli615/lebroncs/blob/main/src/main/java/com/example/sping_portfolio/controllers/grayscale.java#L34-L72)
- [x] [pngs for grayscaled array list](https://github.com/jli615/lebroncs/blob/main/src/main/java/com/example/sping_portfolio/controllers/grayscale.java#L76-L134)

Rohan K [journal](https://docs.google.com/document/d/1O8LDu8Bz1mrTZmrHpIkAkt4K8Yz7Xif-tJv4MuX_HBg/edit) - Contributed to theory regarding model improvements through usage of new array lists and logic from previous labs
- [x] [boolean logic using algorithm](https://github.com/jli615/lebroncs/blob/main/src/main/java/com/example/sping_portfolio/minilabs/GreyScale/GrayScaleMain.java)
- [ ] [controller with new method of using array lists](https://github.com/jli615/lebroncs/blob/main/src/main/java/com/example/sping_portfolio/minilabs/GreyScale/GreyScaleController.java)
- [ ] support jpeg instead of base64 utilizing encryption

**Comment by jm1021** [comment]
Good movement of old tickets into closed status.   Talkin' about using gray scale into their project pages.  One button to flip package back and forth.   Nice breakdown on tickets.

**Comment by jm1021** [comment]
No real breakdown of task on specific tickets.

.8/1

**Comment by somythl** [comment]
I think you guys did great! 4.75/5 for the ponits because you guys were able to demonstrate a runtime link with usage of grayscale and other classes that modify the images. You showed me a good front end while also the class code that works that also completely meets the criteria.

Below is link to reasoning

https://docs.google.com/document/d/1g5QxhOGj4QaqJo2btLYOTnROR6VvoiPXBSss-O1SEC4/edit?usp=sharing

**Comment by jm1021** [comment]
I am disappointed in not seeing a final score after I put so much emphasis on it.  Also, I think the modeling for 3 points may be generous.   It was not clear in video.  I will provide 6.75 / 8 for everyone.
