### ISSUE TITLE
Week 8 Review Ticket

### ISSUE THREAD

**Issue by ghost** [jli615/lebroncs#44]
Total score: 9.5/10
Subscores:
- Team presentation: 4.5/5 (https://docs.google.com/presentation/d/1mBO_E0bQc2UlVU_jX6H95cA40OOUBDsbrW-R-CIlFiA/edit?usp=sharing)
- ASCII art lab: 3/3
- Unit 8: 2/2

N@tM Overview plus runtime:
- [x] [Key features planned for N@tM project ](https://docs.google.com/document/d/1_LjOlISFLZMH3wBM3gS-bPFDvOlh5r11hAoOUuE5qSk/edit?usp=sharing)
- [ ] [Runtime]()(coming)

ASCII Art Lab(on hold):
- [ ] [front end]()
- [ ] [back end]()

Unit 8:
- [x] [Rohan N Journal](https://docs.google.com/document/d/1Dgo7CY2jxnVj65bZKBA6qgkrpPXyoRsbat23JUp7-yU/edit)
- [x] [Justin Journal](https://docs.google.com/document/d/1OPRMwOUsIXQAviD770tt6ad24YB9dVeR5SI8XWJzHYs/edit?usp=sharing)
- [x] [Rohan K Journal](https://docs.google.com/document/d/1O8LDu8Bz1mrTZmrHpIkAkt4K8Yz7Xif-tJv4MuX_HBg/edit)
- [x] [Ryan Journal](https://docs.google.com/document/d/1c0jHTO8-ny1ojF077amTJ0aANaYlL44gPX6CZOGkgEM/edit)

**Comment by jm1021** [comment]
- [x] Review ticket in zoom

1 minute of Project
- [x] Overvew and Purpose
- [ ]  Key features planned for N@tM project 

2 minute runtime
- [x] Show running project
- [ ] Allow others access
- [x] Runtime Feature 1
- [x] Runtime Feature 2
- [ ] Runtime Feature 3

Technical overview
- [x]  Technical Feature 1
- [ ]  Technical Feature 2

Good presentation and usage of idea from mini labs in project.  Good ideas for presenting data.  Good ideas for future input and collection.

Need to consider how to make this dynamic and driven by database as you move forward.  Fun idea for school.

**Comment by lucap2527** [comment]
Honestly not a lot of visual presentation, the information is good though with the points addressed, points gotten, and the people satisfied with a greater common good.

**Comment by somythl** [comment]
I think the idea is great. Would be very cool to see rosters of all our school athletes. I also think you provided a clever way to incorporate the grayscale by honoring graduated seniors.

**Comment by PrishaMaiti** [comment]
Your stats for the DNHS Basketball Page is very organized! I definitely think that a schedule page would make the website a lot more user-friendly

**Comment by abhijay-deevi** [comment]
I liked the idea of including statistics from previous basketball players. I think an API might be a good idea for that. The front end is also pretty good.

**Comment by BillyCherres** [comment]
I really enjoy your front end and the del Norte picture in the front of the website. Very spirated. I love it

**Comment by calebkimsd** [comment]
Our group enjoyed - I like how you integrated grayscaling to your actual website/project (basketball). Stat page looks very clean - and the images of the players/grayscale is very clean.

**Comment by ghost** [comment]
Project looks very strong and it already displayed so much data, so I think that the project is already doing pretty good. Overall well done.

**Comment by yajatyadav** [comment]
I like how you guys implemented the grayscale on your website and how you embedded a video. I would recommend using a database so it is easier to update the list of all the players.

**Comment by 4disease** [comment]
Nice use of tables, the layout is easy to read and accessible. Cool theme as well, I like the sentiment.

**Comment by Akshay-Rohatgi** [comment]
The way you used the grayscale feature with the images to honor the seniors is a very creative implementation!

**Comment by mistylavender** [comment]
I like the use of minilabs and the way you combined two of your interests into one. You displayed plenty of data and tables, so it is very creative!

**Comment by iskapoor** [comment]
This is a creative and needed idea! Your presentation was thorough and well-thought-out. The UI is really clean and to-the-point which is great for a site like this. The video was interesting but not too sure how relevant it is.

**Comment by dsblack0** [comment]
I like how you added information about each of players as well. It might be helpful to add a way to search through the players as well.

**Comment by wiz124** [comment]
Project idea was really cool. I thought the way you guys implemented the minilabs into the website was really creative.

**Comment by LordRoop** [comment]
Cool concept.
Loved how you integrated grayscale into your project.
The video was pretty cool.

**Comment by rachelklee** [comment]
It was cool how you included greyscale as a part of your actual project. The idea you have for your project also seems very well thought out.

**Comment by ChiefGuap** [comment]
I loved this PROJECT! I loved how you included the basketball team and how you implemented the grayscale into a main part of your project. Also, VENUS HOOPS BABY! It was awesome how you included that in your project!

**Comment by rkwreck** [comment]
I love your idea and the way you used the grayscale lab for the seniors is pretty creative. I think it'd be even better if you made your UI design a little cleaner so it's more user-friendly. Great job!

**Comment by alvinzhengq** [comment]
Great data management using Javascript, on the frontend the code is easy to read and understand, and seems to be a very efficient way of achieving what you are going for.

**Comment by chenxin-chex** [comment]
Presentation is clear and explains the code well. The grayscale page code was also clever

**Comment by adhithin** [comment]
it was creative how you used the grayscale for the seniors and integrated that into your project. it was unique to see that incorporation of sports into computer science.

**Comment by SamiDeshatty** [comment]
I like how you used ideas from the minilab and were able to implement it into your own webpage ideas. Very easy to understand front end as well!

**Comment by devamshri** [comment]
The presentation is pretty well designed and I really liked the Venus Hoops video. Just a bit more organization is needed to the project as I didn't really grasp the vision.
