### ISSUE TITLE
Justin Individual Final Review Ticket

### ISSUE THREAD

**Issue by jli615** [jli615/lebroncs#45]

**Comment by ghost** [comment]
**TOTAL SCORE: 5.5/6**

Topic 1
Relation to CB topic: 1/1
Command of Technical Topic: 0.75/1
Vibe: 1/1
Total Score: 2.75/3

Topic 2
Relation to CB topic: 0.75/1
Command of Technical Topic: 1/1
Vibe: 1/1
Total Score: 2.75/3

Comments:
- You did a great job showing each aspect of the code that outputs the result 
- The transitions between different files were well timed and make sense for the purpose of the explanation 
- No issues with quality, making it easy to understand the flow/process of the code 

Improvement:
- For your first topic you could have explained inheritance and methods in the controller class a bit more
- Could have done a better job referencing the relationship to college board in topic 2

**Comment by RohanKoshy** [comment]
TOTAL SCORE: 5.5/6

Topic 1
Relation to CB topic: 1/1
Command of Technical Topic: 1/1
Vibe: 1/1
Total Score: 3/3

Topic 2
Relation to CB topic: 1/1
Command of Technical Topic: 0.5/1
Vibe: 1/1
Total Score: 2.5/3

Comments:

Seemed like you understand the logic of how the code worked with the factorial recursive method

Like how you also spoke on how the values returned from the backend gets passed to the frontend

Enjoyed how, for both features explained, you explicitly explained how it connected to College board topics.

Could have used better vocabulary and terms when explaining the grayscale and factorial

Could have shown better connection to college board videos for grayscale image feature

**Comment by ryanmgds** [comment]
TOTAL SCORE: 5.5/6

Topic 1
Relation to CB topic: 1/1
Command of Technical Topic: 1/1
Vibe: 0.75/1
Total Score: 2.75/3

Topic 2
Relation to CB topic: 0.75/1
Command of Technical Topic: 1/1
Vibe: 1/1
Total Score: 2.75/3

Comments:
-great job showing understanding of code, and explaining how it worked (especially with factorial recursive method)
-I liked your emphasis on relating code to college board topics
-i liked how the features you showed were incorporated well into the actual project

Improvement:
-with grayscale, you could've gone a bit more in depth with code and relation to CB

**Comment by jm1021** [comment]
![image](https://user-images.githubusercontent.com/54686997/139541637-35e5157b-8b5f-4f61-9b2f-e44739744d5e.png)


Memories are talking about loop and talking about controller on images.  Agree with comments above.  Perhaps more like 4.95/6.   Comments are all the same for everyone.  But Koshy was far better.  1.5/2
