### ISSUE TITLE
Rohan Individual Final Review Ticket

### ISSUE THREAD

**Issue by ghost** [jli615/lebroncs#46]
[Video](https://youtu.be/NK_8NJdSe2w)
----------------------------------------------------------------------------------------------------------------------------------------------
**Topic 1 (2D Grids)**: 
- [x] [code](https://github.com/jli615/lebroncs/blob/main/src/main/java/com/example/sping_portfolio/minilabs/Grid2D.java)
**CB Connection**: In College Board Unit 6.3 Daily Video, they talk mainly about enhanced for loops and their relationship with arrays. I knew I would have to use enhanced for loops in order to print out my array, so I referenced this video in order to improve the efficiency of my program's algorithm. All of Unit 6 was helpful because of the important info on arrays that they covered. I also had to refer to 4.2 because of the use of nested for loops. 

**Topic 2 (PBL)**:
- [x] [front end](https://github.com/jli615/lebroncs/blob/552c40d412d0fb1aa606f6847e5068fca7863062/src/main/resources/templates/image.html#L17-L22)
- [x] [back end](https://github.com/jli615/lebroncs/blob/552c40d412d0fb1aa606f6847e5068fca7863062/src/main/java/com/example/sping_portfolio/controllers/grayscale.java#L20-L32)
**PBL Purpose**: My main goal behind making this was to complete the grayscale lab. After thinking about it, I realized this would be a great opportunity to connect it to our project. We made it into a gallery of our team's basketball players, and by using the toggle function, anyone can simply switch between the color and grayscale images of the players.

**Comment by jli615** [comment]
**TOTAL SCORE: 5.5/6**

Topic 1
Relation to CB topic: 1/1
Command of Technical Topic: 1/1
Vibe: 0.75/1
Total Score: 2.75/3

Topic 2
Relation to CB topic: 1/1
Command of Technical Topic: 0.75/1
Vibe: 1/1
Total Score: 2.75/3

Comments:
- solid demonstration of the 2D array function in the terminal
- good explanation of toggle button in grayscale
- good job meshing backend and frontend to provide thorough explanation

Improvement
- could have spent more time explaining the recursion in the grayscale page

**Comment by RohanKoshy** [comment]
TOTAL SCORE: 5.5/6

Topic 1
Relation to CB topic: 1/1
Command of Technical Topic: 0.75/1
Vibe: 0.75/1
Total Score: 2.75/3

Topic 2
Relation to CB topic: 1/1
Command of Technical Topic: 1/1
Vibe: 1/1
Total Score: 2.75/3

Comments:

good vocabulary when explaining the first topic (ex: element, array)
Good job showing that the first feature is running and explaining how it is running while imputing the scanner values
Very little mistakes in presenting, fluid speech throughout proving practice was done for this video

Improvement

Could have explained the reasoning for the first topic,  and why a sports website could use adjustments of rows and columns

**Comment by ryanmgds** [comment]
TOTAL SCORE: 5.5/6

Topic 1
Relation to CB topic: 0.75/1
Command of Technical Topic: 1/1
Vibe: 1/1
Total Score: 2.75/3

Topic 2
Relation to CB topic: 1/1
Command of Technical Topic: 0.75/1
Vibe: 1/1
Total Score: 2.75/3

Comments:
-explained code well, demonstrated you knew what you were doing
-liked how the code used was input into actual project, showed how you took labs and turned into actual work
-well explained toggle button on its use and how it works

Improvement
-could have dove a bit deeper into 2nd topic and how the recursion took place

**Comment by jm1021** [comment]
Topic 1. Input of numbers into 2D array.  Kind of an academic example with no real purpose (Not PBL).  Meets topic, understanding is good.  Vibe not that interesting.
Topic 2. Toggle on page reload.  Would have like to see the "Seniors" button toggle.  I would like to see more depth or growth on this one by now.

4.75/6

Comments are all the same for everyone.  But Koshy was far better.  1.5/2
